#!/bin/bash

function get_this_dir() {
  # Taken from https://stackoverflow.com/questions/59895#246128
  local SOURCE="${BASH_SOURCE[0]}"
  while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$(cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd)"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done
  (cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd)
}

readonly this_dir="$(get_this_dir)"
readonly qmk_root="$(realpath "$this_dir/../../../../")"
readonly keymap="manta60:misawa"
require_sudo=0
operation=""

case "$1" in
  clean)
    operation="clean"
    ;;
  build)
    operation="$keymap"
    ;;
  write)
    operation="$keymap:avrdude"
    require_sudo=1
    ;;
  write-right|write-left)
    operation="$keymap:avrdude-split-$(echo "$1" | cut -d '-' -f 2)"
    require_sudo=1
    ;;
  *)
    echo "Unknown operation $1" >&2
    exit 1
    ;;
esac

su=''
[[ "$require_sudo" -eq 1 ]] && su='sudo'
(cd "$qmk_root" && $su make "$operation")

