#!/bin/bash

function get_this_dir() {
  # Taken from https://stackoverflow.com/questions/59895#246128
  local SOURCE="${BASH_SOURCE[0]}"
  while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$(cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd)"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done
  (cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd)
}

readonly this_dir="$(get_this_dir)"
readonly qmk_root="$(realpath "$this_dir/../../../../")"
readonly keymap="manta60:misawa"
operation=""

case "$1" in
  format)
    operation="qmk cformat -b keyboards/manta60/keymaps/misawa/**/*.[ch]"
    ;;
  clean)
    operation="make clean distclean"
    ;;
  build)
    operation="make $keymap"
    ;;
  write)
    operation="sudo make $keymap:avrdude"
    ;;
  write-right|write-left)
    operation="sudo make $keymap:avrdude-split-$(echo "$1" | cut -d '-' -f 2)"
    ;;
  *)
    echo "Unknown operation $1" >&2
    exit 1
    ;;
esac

(cd "$qmk_root" && $operation)

